---
abstract: 'A Perly markup language.'
author:
  - 'mucker, C<< <mukcer at gmx.com> >>, mucker <mukcer@gmx.com>'
build_requires:
  Capture::Tiny: 0
  ExtUtils::MakeMaker: 6.36
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MarkPerl
no_index:
  directory:
    - t
    - inc
requires:
  Data::Pairs: 0
  HTML::Parser: 0
  Modern::Perl: 0
  Text::Balanced: 0
version: 0.01
